version: "3.7"
services:
  app:
    build:
      args:
        user: awdev
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: sevens
    container_name: sevens-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - sevens

  db:
    image: mysql:5.7
    container_name: sevens-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - sevens

  nginx:
    image: nginx:alpine
    container_name: sevens-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - sevens

networks:
  travellist:
    driver: bridge
